setting up the way unit tests are set up

diff --git a/.github/workflows/codeflash.yml b/.github/workflows/codeflash.yml
--- a/.github/workflows/codeflash.yml
+++ b/.github/workflows/codeflash.yml
@@ -16,6 +16,7 @@ jobs:
     name: Optimize new Python code
     if: ${{ github.actor != 'codeflash-ai[bot]' }}
     runs-on: ubuntu-latest
+    #needs: [setup, lint]
     env:
       CODEFLASH_API_KEY: ${{ secrets.CODEFLASH_API_KEY }}
     steps:
@@ -23,13 +24,32 @@ jobs:
         with:
           fetch-depth: 0
       - name: 🐍 Set up Python 3.12
-        uses: astral-sh/setup-uv@v5
+        uses: actions/setup-python@v5
         with:
           python-version: 3.12
       - name: 📦 Install Environment
-        run: |
-          uv pip install "."
-          uv pip install -r requirements/test.txt
-          uv pip install codeflash
+        uses: ./.github/actions/base-cache
+        with:
+          python-version: 3.12
       - name: ⚡️ Codeflash Optimization
-        run: source .venv/bin/activate && codeflash
+        env:
+          UNS_API_KEY: ${{ secrets.UNS_API_KEY }}
+          TESSERACT_VERSION: "5.5.1"
+          CODEFLASH_API_KEY: ${{ secrets.CODEFLASH_API_KEY }}
+        run: |
+          source .venv/bin/activate
+          sudo apt-get update
+          sudo apt-get install -y libmagic-dev poppler-utils libreoffice
+          sudo add-apt-repository -y ppa:alex-p/tesseract-ocr5
+          sudo apt-get update
+          sudo apt-get install -y tesseract-ocr tesseract-ocr-kor
+          tesseract --version
+          installed_tesseract_version=$(tesseract --version | grep -oP '(?<=tesseract )\d+\.\d+\.\d+')
+          if [ "$installed_tesseract_version" != "${{env.TESSERACT_VERSION}}" ]; then
+            echo "Tesseract version ${{env.TESSERACT_VERSION}} is required but found version $installed_tesseract_version"
+            exit 1
+          fi
+          # FIXME (yao): sometimes there is cache but we still miss argilla in the env; so we add make install-ci again
+          make install-ci
+          pip install codeflash
+          codeflash
